### ISSUE TITLE
Cannot find module 'serialport'

### ISSUE THREAD

**Issue by Muhammad-Adam** [codesbiome/electron-react-webpack-typescript-2022#30]
I need to use this module in my electron application. Looking around, I understand that I need to insert the code below in `webpack.main.js` because `serialport` is a native module.
```
  externals: {
    serialport: 'serialport',
  },
```

I can run the application in developement mode, no problem. But when iItried to run `npm run make` or `npm run pacakge`, and when I click on the executable, it will show the error as the on in the title.

**Comment by codesbiome** [comment]
Hello @Muhammad-Adam 

Seems like you're trying to use `serialport` package : https://www.npmjs.com/package/serialport
It should work without any "externals" in webpack configuration.
We were using same `serialport` native module in some custom projects, there was no issue.

It would be nice if you provide more information regarding what error it displays.

**Comment by Muhammad-Adam** [comment]
@codesbiome 
### Steps to reproduce

1) Clone the minimal version of this repo
2) Install serialport via `npm install serialport`
3) In `main.ts`, create an async function within the `createWindow` function body. Below is an example
```
const testFunc = async () => {
    const temp = await SerialPort.list();
}
```
4) Try `npm start`

Below is the error i have gotten
```App threw an error during load
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=101 uv=1 armv=8 libc=glibc node=16.13.0 electron=17.0.1 webpack=true
    loaded from: /Users/adam/Documents/codeplayground/node/serial-test/.webpack

    at Function.load.path (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:4507:9)
    at load (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:4469:30)
    at Object../node_modules/@serialport/bindings-cpp/dist/load-bindings.js (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:825:46)
    at __webpack_require__ (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:5023:42)
    at Object../node_modules/@serialport/bindings-cpp/dist/darwin.js (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:310:25)
    at __webpack_require__ (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:5023:42)
    at Object../node_modules/@serialport/bindings-cpp/dist/index.js (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:501:18)
    at __webpack_require__ (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:5023:42)
    at Object../node_modules/serialport/dist/serialport.js (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:4729:24)
    at __webpack_require__ (/Users/adam/Documents/codeplayground/node/serial-test/.webpack/main/index.js:5023:42)
```

**Comment by codesbiome** [comment]
@Muhammad-Adam

> Below is the error i have gotten

Seems like the latest `serialport@^10.4.0` will require some additional changes in this project to make it work.


We've been using a previous version `v9.2.5` of serialport without any issues. 
Can you try downgrading the package and see if works?

```json
"serialport": "^9.2.5"
```

**Comment by Muhammad-Adam** [comment]
@codesbiome 

Tested with the older version of `serialport` that you had suggested. Working properly as intended in dev and in production.

Just wondering if I were to use the latest version of `serialport`, what changes should I be making? Because even with the  `externals` field, it will only work in dev environment. If I were to package it and run the app, the error that pops out will be `Cannot find module 'serialport'.

**Comment by Muhammad-Adam** [comment]
@codesbiome any updates? Would love to know your progress on this.

**Comment by codesbiome** [comment]
@Muhammad-Adam 

Seems like there is an issue with `serialport@10` when packaging application for production using electron-forge. There is already on-going discussions regarding this issue in its related repositories.

<br>

In  case of `Cannot find module [serialport]` in packaged (production) app. 
Did you try copying missing modules to `out/resources/app/node_modules` from `node_modules` of project root?
Something like this : 

![image](https://user-images.githubusercontent.com/46080054/176964337-62660eb5-53d7-4548-a07c-e0d433e3ce9c.png)
